version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    restart: unless-stopped
    container_name: ai-hedge-fund-backend

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    container_name: ai-hedge-fund-frontend 