[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
# startCommand removed to use Dockerfile CMD
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 